### ISSUE TITLE
Create New Pet Page - Image Upload Generates Error Message

### ISSUE THREAD

**Issue by EmilyRamirez** [thefonso/kitty-tracker-front-vue#71]
If I try to upload an image before filling in the other fields it generates the errors shown in the screenshot.
![screen shot 2018-07-01 at 8 21 56   ##am](https://user-images.githubusercontent.com/25428524/42134814-1e1e603a-7d08-11e8-9403-9332deae72e6.png)

**Comment by thefonso** [comment]
WONDERFUL ISSUE CREATION! 🙌 👍🏼 
This is as I mentioned in our last meeting. Photo upload is handled on the profile page (/cat/cad_id). That's issue #4 . Still working on doing it for this page also. I don't have an issue for created for this so this is great. 😊 👍🏼
