### ISSUE TITLE
Create New Pet Page - Upload Image Field Is Not Working / Generates New Pet Profile

### ISSUE THREAD

**Issue by EmilyRamirez** [thefonso/kitty-tracker-front-vue#75]
When the "Upload Image" button is clicked it lets me select a picture, but the picture does not appear in the window.  Each time I click on the button to upload an image it generates a new profile.
![screen shot 2018-07-01 at 8 48 39 am](https://user-images.githubusercontent.com/25428524/42135080-f19cd948-7d0b-11e8-8d80-eb6b343670ca.png)

**Comment by thefonso** [comment]
is this the same issue as #71 ?

**Comment by EmilyRamirez** [comment]
It's related to #71, except if you fill in all the other fields on the "Create Pet" page and then upload a pic it doesn't generate an error message and creates a new cat profile.
