### ISSUE TITLE
Create New Pet Page - Litter Name Field Not Working

### ISSUE THREAD

**Issue by EmilyRamirez** [thefonso/kitty-tracker-front-vue#76]
I can't type or select anything in the "Litter Name" field.
![screen shot 2018-07-01 at 8 55 01 am](https://user-images.githubusercontent.com/25428524/42135201-1e7d3df8-7d0d-11e8-9735-7282ec97b821.png)

**Comment by thefonso** [comment]
ah...probably because it's not set up to associate a new kitten a litter from there...but I see where you wanna go. 🤝👍🏼
