### ISSUE TITLE
Feedings Page - Link Back to Pet Record Page

### ISSUE THREAD

**Issue by EmilyRamirez** [thefonso/kitty-tracker-front-vue#80]
I was thinking it would be a good idea if we linked the Feedings page back to the Pet Record page by clicking on the pets name at the top of the page.
![screen shot 2018-07-01 at 9 34 19 am](https://user-images.githubusercontent.com/25428524/42135570-3a161cec-7d12-11e8-8b51-2436d0a86017.png)

**Comment by thefonso** [comment]
yeah...I had same idea too.
