### ISSUE TITLE
Add A Cat Page - Can't Continue to Next Page If Non-Integer is Entered, Even if Corrected

### ISSUE THREAD

**Issue by EmilyRamirez** [thefonso/kitty-tracker-front-vue#91]
Typing a non-integer into the "Weight" field generates the notice shown in the screen shot.  I can't move forward with the "Submit" or "Next" buttons even after error has been corrected.
![add a cat - weight error](https://user-images.githubusercontent.com/25428524/42732490-2edff812-87e8-11e8-8533-e48f2c6cd6b2.png)

**Comment by thefonso** [comment]
NOTE: empty space at end of entry leaves the error. As a user the fields clear out when errored and reselected
