### ISSUE TITLE
Add a Cat Page - Failed Profile Creation

### ISSUE THREAD

**Issue by EmilyRamirez** [thefonso/kitty-tracker-front-vue#93]
Profile creation fails with the following steps: 
1. Create a new cat then click the "Next" button
2. Choose not to add a photo on the "Add Profile Photo" tab 
3. Hit the "Next" button 
4. I get the pop up that says it was successful but it doesn't get saved.  

Console error in the screen shot is after I skipped adding a picture and the profile did not get created.
![console errors for failed profile save](https://user-images.githubusercontent.com/25428524/42732898-1bce88b8-87ef-11e8-8dcd-21da3de3aa01.png)

**Comment by thefonso** [comment]
followed same steps...got a new cat with default pic, as expected, so closing this one.

**Comment by thefonso** [comment]
(NOTE: ask Emily to try and reproduce, now that code is updated)
