### ISSUE TITLE
Add a Cat Page - Birthday Field

### ISSUE THREAD

**Issue by EmilyRamirez** [thefonso/kitty-tracker-front-vue#95]
Can we change the "Birthday" field format to month-day-year and add the date picker widget?
![date picker](https://user-images.githubusercontent.com/25428524/42733281-4d3f9950-87f4-11e8-8d7e-2b5dfd2dc440.png)

**Comment by thefonso** [comment]
Per our chat earlier this week, I'll add this in the new "add a cat" form design once it's ready.

**Comment by thefonso** [comment]
Done
