### ISSUE TITLE
Add a Cat Page - Litter Name Field

### ISSUE THREAD

**Issue by EmilyRamirez** [thefonso/kitty-tracker-front-vue#96]
You're probably already working on this, so sorry if it is a duplicate. Can we set up the "Litter Name" field so the user can manually type the litter name in, then have it populate in the "Litter" field on their profile summary?

![litter name](https://user-images.githubusercontent.com/25428524/42733461-531fc72a-87f7-11e8-9964-4a6c7a3b7c3f.png)

**Comment by thefonso** [comment]
I've adjusted it ...take a look and tell me what you think.
